name: BlockHunt
main: nl.Steffion.BlockHunt.BlockHunt
version: 0.1.4_ALPHA
authors:
  - Steffion
description: An easy to set up, Hide and seek plugin. Hide as blocks from the killer seekers.
softdepend: [DisguiseCraft, ProtocolLib]
load: POSTWORLD
commands:
  BlockHunt:
    usage: /<command>
    description: N/A
    aliases:
        - bh
        - prophunt
        - hideandseek
        - has
        - hs
        - seekandfind
        - saf
        - sf